### GET ALL BOOKS
GET http://localhost:5500/books HTTP/1.1

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### GET ALL BOOKS SORTED BY AUTHOR (DESCENDING)
GET http://localhost:5500/books?sortBy=author&order=desc HTTP/1.1

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### GET ALL BOOKS AND HIDE ATTRIBUTES
GET http://localhost:5500/books?hide=isbn,imgUrl HTTP/1.1

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### GET ONE BOOK (FIRST OF SEED)
GET http://localhost:5500/books/9781806982516 HTTP/1.1

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### GET ONE BOOK - NOT FOUND
GET http://localhost:5500/books/0000000000000 HTTP/1.1

> {%
    client.test("Request failed as expected", function() {
        client.assert(response.status === 404, "Response status is not 404");
    });
%}

### POST REQUEST TO UPDATE LIST (RESET)
POST http://localhost:5500/books/reset HTTP/1.1

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### POST BOOK - NOT FOUND (INVALID ISBN)
POST http://localhost:5500/books/0000000000000 HTTP/1.1

> {%
    client.test("Post book not found", function() {
        client.assert(response.status === 404, "Expected code 404, got: " + response.status);
    });
%}

### ADD NEW BOOK
POST http://localhost:5500/books/9781853260001 HTTP/1.1

> {%
    client.test("Post book successful", function() {
        client.assert(response.status === 201, "Expected code 201, got: " + response.status);
    })
%}

### REMOVE BOOK
DELETE http://localhost:5500/books/9781853260001 HTTP/1.1

> {%
    client.test("Delete book successful", function() {
        client.assert(response.status === 204, "Expected code 204, got: " + response.status);
    })
%}

### DELETE NON-EXISTENT BOOK
DELETE http://localhost:5500/books/1234567890123 HTTP/1.1

> {%
    client.test("Expect 404 for non-existent book", function() {
        client.assert(response.status === 404, "Response status is not 404");
    });
%}

### GET ALL SHELVES
GET http://localhost:5500/shelves HTTP/1.1

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### CREATE A NEW SHELF
POST http://localhost:5500/shelves/ScienceFiction HTTP/1.1

> {%
    client.test("Create shelf", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### CREATE SHELF WITH INVALID NAME (EMPTY)
POST http://localhost:5500/shelves/%20 HTTP/1.1

> {%
    client.test("Expect 400 for invalid shelf name", function() {
        client.assert(response.status === 400, "Response status is not 400");
    });
%}

### ASSIGN BOOK TO SHELVES
POST http://localhost:5500/shelves/ HTTP/1.1
Content-Type: application/json

{
  "isbn": "9781806982516",
  "shelves": ["ScienceFiction", "Favorites"]
}

> {%
    client.test("Add book to shelf", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}